services:
  server:
    build:
      context: .
      target: base
    environment:
      - NODE_ENV=development
      - NEXT_WEBPACK_USEPOLLING=1
      - DATABASE_URL=postgresql://user:password@db:5432/gym_tracker?schema=public
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./prisma:/usr/src/app/prisma
    depends_on:
      - db
    command: >
      sh -c "npx prisma migrate deploy &&
             npm run dev"

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gym_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data:
